name: chocolatine
run-name: ${{ github.actor }} checker
on: 
  push:
    branches-ignores:
      - " ga-ignore-"
  pull_request:
    branches-ignores:
      - " ga-ignore-"
jobs:
  coding-style-checker:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: ""

      - name: Coding Style
        run: check.sh . /tmp

      - name: Annotations Coding Style
        run: |
          input=/tmp/coding-style-reports.log
          while IFS= read -r line; do
            IFS=':' read -r file n_line title err <<< "$line"
            echo "::error title=${title} coding style error,file=${file},line=${n_line}::${err}"
          done < $input

      - name: Report Results
        run: |
          NBE=$(cat /tmp/coding-style-reports.log | wc -l)
          if [ $NBE -gt 0 ]; then
            exit 1
          fi
